### ISSUE TITLE
incorrect 8bpc output

### ISSUE THREAD

**Issue by g-rden** [shinyblink/ffshot#3]
https://github.com/shinyblink/ffshot/blob/853b1eb3181affde1b56d6e364fe201f8260d0d0/ffshot.c#L141-L143
For 8bpc it outputs `00 15 00 21 00 32` instead of `15 15 21 21 32 32` for example.

From the official png2ff.c file:
```
switch(png_get_bit_depth(pngs, pngi)) {
case 8:
for (r = 0; r < height; ++r) {
    for (i = 0; i < rowlen; i++) {
        row[i] = htons(257 * pngrows[r][i]);
    }
    efwrite(row, sizeof(uint16_t), rowlen, stdout);
}
```
My (stupid) fix would be to replace lines 141 to 143 with this:
```
if (bpc == 8) {
	img[p + 0] = htobe16(r * 257);
	img[p + 1] = htobe16(g * 257);
	img[p + 2] = htobe16(b * 257);
} else {
	img[p + 0] = htobe16(r << scale);
	img[p + 1] = htobe16(g << scale);
	img[p + 2] = htobe16(b << scale);
}
```

**Comment by vifino** [comment]
Oh, yes! You're 100% correct. 
The thing that is happening is because of the shift, the remaining bits do not get filled.

I'll fix this in a second (without the extra branching)
